apiVersion: v1
kind: ReplicationController
metadata:
  name: HazleCast1
  namespace: test
spec:
  replicas: test
  selector:
    app: HazleCast1
  template:
    metadata:
      labels:
        app: HazleCast1
    spec:
      serviceAccount: test
      containers:
      - name: HazleCast1
        image: test/test/HazleCast1:latest
        imagePullPolicy: Always
        ports:
         - containerPort: 8080
        volumeMounts:
        - name: ocnp-cluster-info
          mountPath: /ocnp-cluster-info
      #side container to extract cluster name info
      - name: info
        image: zlp11313.vci.att.com:5100/com.att.ocnp.mgmt/cluster-info:1.0
        volumeMounts:
        - name: ocnp-cluster-info
          mountPath: /ocnp-cluster-info
      volumes:
      # volume for cluster name info
      - name: ocnp-cluster-info
        emptyDir: {}